services:
  jupyter:
    build: .
    container_name: jupyter_notebook
    volumes:
      - ./notebooks:/app/notebooks
      - ./data:/app/data
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DATABASE_URL=${DATABASE_URL}  # Load Supabase URL from .env file
